spring:
  application:
    name: springboot-rabbitmq-order-system-backend
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/food_ordering
      username: postgres
      password: 332003
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_ordering
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10
    template:
      exchange: orderExchange
      routing-key: order.routingKey
    restaurantQueuePrefix: "restaurant.queue."
server:
  port: 4242
